package com.lean.moneynote.mapper;

import com.lean.moneynote.model.Catagory;
import com.lean.moneynote.model.CatagoryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CatagoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table catagory
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	long countByExample(CatagoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table catagory
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	int deleteByExample(CatagoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table catagory
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table catagory
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	int insert(Catagory row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table catagory
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	int insertSelective(Catagory row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table catagory
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	List<Catagory> selectByExample(CatagoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table catagory
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	Catagory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table catagory
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Catagory row, @Param("example") CatagoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table catagory
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	int updateByExample(@Param("row") Catagory row, @Param("example") CatagoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table catagory
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	int updateByPrimaryKeySelective(Catagory row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table catagory
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	int updateByPrimaryKey(Catagory row);
}