package com.lean.moneynote.model;

import java.util.Date;

public class Catagory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column catagory.Id
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column catagory.name
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column catagory.icon
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column catagory.budget
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	private Long budget;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column catagory.created_at
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column catagory.updated_at
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column catagory.modified_at
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	private Date modifiedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column catagory.Id
	 * @return  the value of catagory.Id
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column catagory.Id
	 * @param id  the value for catagory.Id
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column catagory.name
	 * @return  the value of catagory.name
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column catagory.name
	 * @param name  the value for catagory.name
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column catagory.icon
	 * @return  the value of catagory.icon
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column catagory.icon
	 * @param icon  the value for catagory.icon
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column catagory.budget
	 * @return  the value of catagory.budget
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	public Long getBudget() {
		return budget;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column catagory.budget
	 * @param budget  the value for catagory.budget
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	public void setBudget(Long budget) {
		this.budget = budget;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column catagory.created_at
	 * @return  the value of catagory.created_at
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column catagory.created_at
	 * @param createdAt  the value for catagory.created_at
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column catagory.updated_at
	 * @return  the value of catagory.updated_at
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column catagory.updated_at
	 * @param updatedAt  the value for catagory.updated_at
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column catagory.modified_at
	 * @return  the value of catagory.modified_at
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	public Date getModifiedAt() {
		return modifiedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column catagory.modified_at
	 * @param modifiedAt  the value for catagory.modified_at
	 * @mbg.generated  Sat Oct 22 10:38:40 ICT 2022
	 */
	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}
}