package com.lean.moneynote.model;

import java.util.Date;

public class Ledger {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ledger.LedgerID
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	private Integer ledgerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ledger.Transaction_type
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	private String transactionType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ledger.Money
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	private Long money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ledger.description
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ledger.created_at
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ledger.updated_at
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ledger.modified_at
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	private Date modifiedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ledger.catagory_id
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	private Integer catagoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ledger.account_id
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	private Integer accountId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ledger.LedgerID
	 * @return  the value of ledger.LedgerID
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public Integer getLedgerid() {
		return ledgerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ledger.LedgerID
	 * @param ledgerid  the value for ledger.LedgerID
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public void setLedgerid(Integer ledgerid) {
		this.ledgerid = ledgerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ledger.Transaction_type
	 * @return  the value of ledger.Transaction_type
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public String getTransactionType() {
		return transactionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ledger.Transaction_type
	 * @param transactionType  the value for ledger.Transaction_type
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ledger.Money
	 * @return  the value of ledger.Money
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public Long getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ledger.Money
	 * @param money  the value for ledger.Money
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public void setMoney(Long money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ledger.description
	 * @return  the value of ledger.description
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ledger.description
	 * @param description  the value for ledger.description
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ledger.created_at
	 * @return  the value of ledger.created_at
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ledger.created_at
	 * @param createdAt  the value for ledger.created_at
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ledger.updated_at
	 * @return  the value of ledger.updated_at
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ledger.updated_at
	 * @param updatedAt  the value for ledger.updated_at
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ledger.modified_at
	 * @return  the value of ledger.modified_at
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public Date getModifiedAt() {
		return modifiedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ledger.modified_at
	 * @param modifiedAt  the value for ledger.modified_at
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ledger.catagory_id
	 * @return  the value of ledger.catagory_id
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public Integer getCatagoryId() {
		return catagoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ledger.catagory_id
	 * @param catagoryId  the value for ledger.catagory_id
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public void setCatagoryId(Integer catagoryId) {
		this.catagoryId = catagoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ledger.account_id
	 * @return  the value of ledger.account_id
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public Integer getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ledger.account_id
	 * @param accountId  the value for ledger.account_id
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}
}