package com.lean.moneynote.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LedgerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public LedgerExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andLedgeridIsNull() {
			addCriterion("LedgerID is null");
			return (Criteria) this;
		}

		public Criteria andLedgeridIsNotNull() {
			addCriterion("LedgerID is not null");
			return (Criteria) this;
		}

		public Criteria andLedgeridEqualTo(Integer value) {
			addCriterion("LedgerID =", value, "ledgerid");
			return (Criteria) this;
		}

		public Criteria andLedgeridNotEqualTo(Integer value) {
			addCriterion("LedgerID <>", value, "ledgerid");
			return (Criteria) this;
		}

		public Criteria andLedgeridGreaterThan(Integer value) {
			addCriterion("LedgerID >", value, "ledgerid");
			return (Criteria) this;
		}

		public Criteria andLedgeridGreaterThanOrEqualTo(Integer value) {
			addCriterion("LedgerID >=", value, "ledgerid");
			return (Criteria) this;
		}

		public Criteria andLedgeridLessThan(Integer value) {
			addCriterion("LedgerID <", value, "ledgerid");
			return (Criteria) this;
		}

		public Criteria andLedgeridLessThanOrEqualTo(Integer value) {
			addCriterion("LedgerID <=", value, "ledgerid");
			return (Criteria) this;
		}

		public Criteria andLedgeridIn(List<Integer> values) {
			addCriterion("LedgerID in", values, "ledgerid");
			return (Criteria) this;
		}

		public Criteria andLedgeridNotIn(List<Integer> values) {
			addCriterion("LedgerID not in", values, "ledgerid");
			return (Criteria) this;
		}

		public Criteria andLedgeridBetween(Integer value1, Integer value2) {
			addCriterion("LedgerID between", value1, value2, "ledgerid");
			return (Criteria) this;
		}

		public Criteria andLedgeridNotBetween(Integer value1, Integer value2) {
			addCriterion("LedgerID not between", value1, value2, "ledgerid");
			return (Criteria) this;
		}

		public Criteria andTransactionTypeIsNull() {
			addCriterion("Transaction_type is null");
			return (Criteria) this;
		}

		public Criteria andTransactionTypeIsNotNull() {
			addCriterion("Transaction_type is not null");
			return (Criteria) this;
		}

		public Criteria andTransactionTypeEqualTo(String value) {
			addCriterion("Transaction_type =", value, "transactionType");
			return (Criteria) this;
		}

		public Criteria andTransactionTypeNotEqualTo(String value) {
			addCriterion("Transaction_type <>", value, "transactionType");
			return (Criteria) this;
		}

		public Criteria andTransactionTypeGreaterThan(String value) {
			addCriterion("Transaction_type >", value, "transactionType");
			return (Criteria) this;
		}

		public Criteria andTransactionTypeGreaterThanOrEqualTo(String value) {
			addCriterion("Transaction_type >=", value, "transactionType");
			return (Criteria) this;
		}

		public Criteria andTransactionTypeLessThan(String value) {
			addCriterion("Transaction_type <", value, "transactionType");
			return (Criteria) this;
		}

		public Criteria andTransactionTypeLessThanOrEqualTo(String value) {
			addCriterion("Transaction_type <=", value, "transactionType");
			return (Criteria) this;
		}

		public Criteria andTransactionTypeLike(String value) {
			addCriterion("Transaction_type like", value, "transactionType");
			return (Criteria) this;
		}

		public Criteria andTransactionTypeNotLike(String value) {
			addCriterion("Transaction_type not like", value, "transactionType");
			return (Criteria) this;
		}

		public Criteria andTransactionTypeIn(List<String> values) {
			addCriterion("Transaction_type in", values, "transactionType");
			return (Criteria) this;
		}

		public Criteria andTransactionTypeNotIn(List<String> values) {
			addCriterion("Transaction_type not in", values, "transactionType");
			return (Criteria) this;
		}

		public Criteria andTransactionTypeBetween(String value1, String value2) {
			addCriterion("Transaction_type between", value1, value2, "transactionType");
			return (Criteria) this;
		}

		public Criteria andTransactionTypeNotBetween(String value1, String value2) {
			addCriterion("Transaction_type not between", value1, value2, "transactionType");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNull() {
			addCriterion("Money is null");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNotNull() {
			addCriterion("Money is not null");
			return (Criteria) this;
		}

		public Criteria andMoneyEqualTo(Long value) {
			addCriterion("Money =", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotEqualTo(Long value) {
			addCriterion("Money <>", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThan(Long value) {
			addCriterion("Money >", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThanOrEqualTo(Long value) {
			addCriterion("Money >=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThan(Long value) {
			addCriterion("Money <", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThanOrEqualTo(Long value) {
			addCriterion("Money <=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyIn(List<Long> values) {
			addCriterion("Money in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotIn(List<Long> values) {
			addCriterion("Money not in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyBetween(Long value1, Long value2) {
			addCriterion("Money between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotBetween(Long value1, Long value2) {
			addCriterion("Money not between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Date value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Date value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Date value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Date> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(Date value) {
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(Date value) {
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<Date> values) {
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andModifiedAtIsNull() {
			addCriterion("modified_at is null");
			return (Criteria) this;
		}

		public Criteria andModifiedAtIsNotNull() {
			addCriterion("modified_at is not null");
			return (Criteria) this;
		}

		public Criteria andModifiedAtEqualTo(Date value) {
			addCriterion("modified_at =", value, "modifiedAt");
			return (Criteria) this;
		}

		public Criteria andModifiedAtNotEqualTo(Date value) {
			addCriterion("modified_at <>", value, "modifiedAt");
			return (Criteria) this;
		}

		public Criteria andModifiedAtGreaterThan(Date value) {
			addCriterion("modified_at >", value, "modifiedAt");
			return (Criteria) this;
		}

		public Criteria andModifiedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("modified_at >=", value, "modifiedAt");
			return (Criteria) this;
		}

		public Criteria andModifiedAtLessThan(Date value) {
			addCriterion("modified_at <", value, "modifiedAt");
			return (Criteria) this;
		}

		public Criteria andModifiedAtLessThanOrEqualTo(Date value) {
			addCriterion("modified_at <=", value, "modifiedAt");
			return (Criteria) this;
		}

		public Criteria andModifiedAtIn(List<Date> values) {
			addCriterion("modified_at in", values, "modifiedAt");
			return (Criteria) this;
		}

		public Criteria andModifiedAtNotIn(List<Date> values) {
			addCriterion("modified_at not in", values, "modifiedAt");
			return (Criteria) this;
		}

		public Criteria andModifiedAtBetween(Date value1, Date value2) {
			addCriterion("modified_at between", value1, value2, "modifiedAt");
			return (Criteria) this;
		}

		public Criteria andModifiedAtNotBetween(Date value1, Date value2) {
			addCriterion("modified_at not between", value1, value2, "modifiedAt");
			return (Criteria) this;
		}

		public Criteria andCatagoryIdIsNull() {
			addCriterion("catagory_id is null");
			return (Criteria) this;
		}

		public Criteria andCatagoryIdIsNotNull() {
			addCriterion("catagory_id is not null");
			return (Criteria) this;
		}

		public Criteria andCatagoryIdEqualTo(Integer value) {
			addCriterion("catagory_id =", value, "catagoryId");
			return (Criteria) this;
		}

		public Criteria andCatagoryIdNotEqualTo(Integer value) {
			addCriterion("catagory_id <>", value, "catagoryId");
			return (Criteria) this;
		}

		public Criteria andCatagoryIdGreaterThan(Integer value) {
			addCriterion("catagory_id >", value, "catagoryId");
			return (Criteria) this;
		}

		public Criteria andCatagoryIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("catagory_id >=", value, "catagoryId");
			return (Criteria) this;
		}

		public Criteria andCatagoryIdLessThan(Integer value) {
			addCriterion("catagory_id <", value, "catagoryId");
			return (Criteria) this;
		}

		public Criteria andCatagoryIdLessThanOrEqualTo(Integer value) {
			addCriterion("catagory_id <=", value, "catagoryId");
			return (Criteria) this;
		}

		public Criteria andCatagoryIdIn(List<Integer> values) {
			addCriterion("catagory_id in", values, "catagoryId");
			return (Criteria) this;
		}

		public Criteria andCatagoryIdNotIn(List<Integer> values) {
			addCriterion("catagory_id not in", values, "catagoryId");
			return (Criteria) this;
		}

		public Criteria andCatagoryIdBetween(Integer value1, Integer value2) {
			addCriterion("catagory_id between", value1, value2, "catagoryId");
			return (Criteria) this;
		}

		public Criteria andCatagoryIdNotBetween(Integer value1, Integer value2) {
			addCriterion("catagory_id not between", value1, value2, "catagoryId");
			return (Criteria) this;
		}

		public Criteria andAccountIdIsNull() {
			addCriterion("account_id is null");
			return (Criteria) this;
		}

		public Criteria andAccountIdIsNotNull() {
			addCriterion("account_id is not null");
			return (Criteria) this;
		}

		public Criteria andAccountIdEqualTo(Integer value) {
			addCriterion("account_id =", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotEqualTo(Integer value) {
			addCriterion("account_id <>", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdGreaterThan(Integer value) {
			addCriterion("account_id >", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("account_id >=", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLessThan(Integer value) {
			addCriterion("account_id <", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLessThanOrEqualTo(Integer value) {
			addCriterion("account_id <=", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdIn(List<Integer> values) {
			addCriterion("account_id in", values, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotIn(List<Integer> values) {
			addCriterion("account_id not in", values, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdBetween(Integer value1, Integer value2) {
			addCriterion("account_id between", value1, value2, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotBetween(Integer value1, Integer value2) {
			addCriterion("account_id not between", value1, value2, "accountId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ledger
	 * @mbg.generated  Fri Oct 21 18:37:19 ICT 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledger
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 21 18:22:10 ICT 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}